In [1]:
import torch
import sys
import re
import pandas as pd
from tqdm import tqdm
import os
import json

from llama_index.core.vector_stores import MetadataFilters, ExactMatchFilter
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from transformers import AutoModelForCausalLM, AutoTokenizer
# from llama_index.llms.huggingface import HuggingFaceLLM
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, Document
from llama_index.core.node_parser import SentenceSplitter, SemanticSplitterNodeParser

from llama_index.core.ingestion import IngestionPipeline, IngestionCache
from llama_index.core import StorageContext
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.evaluation import SemanticSimilarityEvaluator
from llama_index.core.ingestion import IngestionPipeline

from huggingface_hub import login

from llama_index.core import PromptTemplate
import warnings, logging
from datasets import Dataset
import importlib.metadata
login(token="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")

from pathlib import Path
import requests
import logging
logging.basicConfig(level=logging.WARNING)
# Force reset the root logger level
logging.getLogger().setLevel(logging.WARNING)
logging.getLogger("urllib3").setLevel(logging.WARNING)
logging.getLogger("urllib3.connectionpool").setLevel(logging.WARNING)
from llama_index.llms.huggingface import HuggingFaceLLM
from sklearn.metrics.pairwise import cosine_similarity
import fitz
import pickle
from helpers.rtr_passage_tagging import DocTagging
from flair.data import Sentence
from flair.nn import Classifier
tagger = Classifier.load('ner-fast')

/Users/mravi/miniconda3/envs/wf_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

2026-04-26 19:11:38,858 SequenceTagger predicts: Dictionary with 20 tags: <unk>, O, S-ORG, S-MISC, B-PER, E-PER, S-LOC, B-ORG, E-ORG, I-PER, S-PER, B-MISC, I-MISC, E-MISC, I-ORG, B-LOC, E-LOC, I-LOC, <START>, <STOP>

In [2]:
state_names=["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]

In [3]:
with open('nodes/semantic_nodes_news.pkl', 'rb') as f1, open('nodes/semantic_nodes_pdf.pkl', 'rb') as f2:
    news = pickle.load(f1)
    pdf = pickle.load(f2)

In [ ]:
print(len(news))

7311

:

In [13]:
import pickle
import gc
import torch
from flair.data import Sentence
import threading
from concurrent.futures import ThreadPoolExecutor

def save_checkpoint(loaded_pkl, output_path, start, total):
    with open(output_path, "wb") as f:
        pickle.dump(loaded_pkl, f)
    print(f"Checkpoint saved at {start}/{total}")

def normalize_locations(locations):
    mapping = {
        "U.S.": "United States",
        "U.S": "United States",
        "US": "United States",
        "USA": "United States",
        "U.S.A.": "United States",
        "United States of America": "United States",
    }
    normalized = []
    for loc in locations:
        normalized.append(mapping.get(loc.strip(), loc.strip()))
    return list(set(normalized))

def extract_locations_from_sentence(sentence):
    locs = []
    for entity in sentence.get_spans("ner"):
        label = entity.get_label("ner")
        if label.value == "LOC" and label.score >= 0.85:
            locs.append(entity.text)
    locs=normalize_locations(list(set(locs)))
    return locs

def process_pkl_batched(loaded_pkl, style, batch_size):  
    total = len(loaded_pkl)
    output_path = f"nodes/semantic_nodes_{style}_with_locations.pkl"
    checkpoint_thread = None

    with torch.no_grad():
        with ThreadPoolExecutor(max_workers=4) as executor:  
            for start in range(0, total, batch_size):
                end = min(start + batch_size, total)
                batch_nodes = loaded_pkl[start:end]
                sentences = list(executor.map(lambda node: Sentence(node.text), batch_nodes))
                tagger.predict(
                    sentences,
                    mini_batch_size=batch_size, 
                    verbose=False,
                )
                for node, sentence in zip(batch_nodes, sentences):
                    node.metadata["extracted_geographies"] = extract_locations_from_sentence(sentence)
                    sentence.clear_embeddings()
                del sentences
                del batch_nodes
                gc.collect()  
                if start % (batch_size) == 0 and start > 0:
                    if checkpoint_thread:
                        checkpoint_thread.join()
                    checkpoint_thread = threading.Thread(
                        target=save_checkpoint, args=(loaded_pkl, output_path, start, total)
                    )
                    checkpoint_thread.start()

                if start % (batch_size) == 0:
                    print(f"Progress is at Node {start}/{total}")

    if checkpoint_thread:
        checkpoint_thread.join()
    with open(output_path, "wb") as f:
        pickle.dump(loaded_pkl, f)
    print(f"Processed {len(loaded_pkl)} nodes. Saved to {output_path}")
    return loaded_pkl
# for node in news:
#     if len(node.text) > 20000:
#         node.text = node.text[:5000]

# processed = process_pkl_batched(news, "news", batch_size=64)

for node in pdf:
    if len(node.text) > 20000:
        node.text = node.text[:5000]

processed = process_pkl_batched(pdf, "pdf", batch_size=64)

Progress is at Node 0/5664
Progress is at Node 64/5664
Checkpoint saved at 64/5664
Progress is at Node 128/5664
Checkpoint saved at 128/5664
Progress is at Node 192/5664
Checkpoint saved at 192/5664
Progress is at Node 256/5664
Checkpoint saved at 256/5664
Progress is at Node 320/5664
Checkpoint saved at 320/5664
Progress is at Node 384/5664
Checkpoint saved at 384/5664
Progress is at Node 448/5664
Checkpoint saved at 448/5664
Progress is at Node 512/5664
Checkpoint saved at 512/5664
Progress is at Node 576/5664
Checkpoint saved at 576/5664
Progress is at Node 640/5664
Checkpoint saved at 640/5664
Progress is at Node 704/5664
Checkpoint saved at 704/5664
Progress is at Node 768/5664
Checkpoint saved at 768/5664
Progress is at Node 832/5664
Checkpoint saved at 832/5664
Progress is at Node 896/5664
Checkpoint saved at 896/5664
Progress is at Node 960/5664
Checkpoint saved at 960/5664
Progress is at Node 1024/5664
Checkpoint saved at 1024/5664
Progress is at Node 1088/5664
Checkpoint saved at 1088/5664
Progress is at Node 1152/5664
Checkpoint saved at 1152/5664
Progress is at Node 1216/5664
Checkpoint saved at 1216/5664
Progress is at Node 1280/5664
Checkpoint saved at 1280/5664
Progress is at Node 1344/5664
Checkpoint saved at 1344/5664
Progress is at Node 1408/5664
Checkpoint saved at 1408/5664
Progress is at Node 1472/5664
Checkpoint saved at 1472/5664
Progress is at Node 1536/5664
Checkpoint saved at 1536/5664
Progress is at Node 1600/5664
Checkpoint saved at 1600/5664
Progress is at Node 1664/5664
Checkpoint saved at 1664/5664
Progress is at Node 1728/5664
Checkpoint saved at 1728/5664
Progress is at Node 1792/5664
Checkpoint saved at 1792/5664
Progress is at Node 1856/5664
Checkpoint saved at 1856/5664
Progress is at Node 1920/5664
Checkpoint saved at 1920/5664
Progress is at Node 1984/5664
Checkpoint saved at 1984/5664
Progress is at Node 2048/5664
Checkpoint saved at 2048/5664
Progress is at Node 2112/5664
Checkpoint saved at 2112/5664
Progress is at Node 2176/5664
Checkpoint saved at 2176/5664
Progress is at Node 2240/5664
Checkpoint saved at 2240/5664
Progress is at Node 2304/5664
Checkpoint saved at 2304/5664
Progress is at Node 2368/5664
Checkpoint saved at 2368/5664
Progress is at Node 2432/5664
Checkpoint saved at 2432/5664
Progress is at Node 2496/5664
Checkpoint saved at 2496/5664
Progress is at Node 2560/5664
Checkpoint saved at 2560/5664
Progress is at Node 2624/5664
Checkpoint saved at 2624/5664
Progress is at Node 2688/5664
Checkpoint saved at 2688/5664
Progress is at Node 2752/5664
Checkpoint saved at 2752/5664
Progress is at Node 2816/5664
Checkpoint saved at 2816/5664
Progress is at Node 2880/5664
Checkpoint saved at 2880/5664
Progress is at Node 2944/5664
Checkpoint saved at 2944/5664
Progress is at Node 3008/5664
Checkpoint saved at 3008/5664
Progress is at Node 3072/5664
Checkpoint saved at 3072/5664
Progress is at Node 3136/5664
Checkpoint saved at 3136/5664
Progress is at Node 3200/5664
Checkpoint saved at 3200/5664
Progress is at Node 3264/5664
Checkpoint saved at 3264/5664
Progress is at Node 3328/5664
Checkpoint saved at 3328/5664
Progress is at Node 3392/5664
Checkpoint saved at 3392/5664
Progress is at Node 3456/5664
Checkpoint saved at 3456/5664
Progress is at Node 3520/5664
Checkpoint saved at 3520/5664
Progress is at Node 3584/5664
Checkpoint saved at 3584/5664
Progress is at Node 3648/5664
Checkpoint saved at 3648/5664
Progress is at Node 3712/5664
Checkpoint saved at 3712/5664
Progress is at Node 3776/5664
Checkpoint saved at 3776/5664
Progress is at Node 3840/5664
Checkpoint saved at 3840/5664
Progress is at Node 3904/5664
Checkpoint saved at 3904/5664
Progress is at Node 3968/5664
Checkpoint saved at 3968/5664
Progress is at Node 4032/5664
Checkpoint saved at 4032/5664
Progress is at Node 4096/5664
Checkpoint saved at 4096/5664
Progress is at Node 4160/5664
Checkpoint saved at 4160/5664
Progress is at Node 4224/5664
Checkpoint saved at 4224/5664
Progress is at Node 4288/5664
Checkpoint saved at 4288/5664
Progress is at Node 4352/5664
Checkpoint saved at 4352/5664
Progress is at Node 4416/5664
Checkpoint saved at 4416/5664
Progress is at Node 4480/5664
Checkpoint saved at 4480/5664
Progress is at Node 4544/5664
Checkpoint saved at 4544/5664
Progress is at Node 4608/5664
Checkpoint saved at 4608/5664
Progress is at Node 4672/5664
Checkpoint saved at 4672/5664
Progress is at Node 4736/5664
Checkpoint saved at 4736/5664
Progress is at Node 4800/5664
Checkpoint saved at 4800/5664
Progress is at Node 4864/5664
Checkpoint saved at 4864/5664
Progress is at Node 4928/5664
Checkpoint saved at 4928/5664
Progress is at Node 4992/5664
Checkpoint saved at 4992/5664
Progress is at Node 5056/5664
Checkpoint saved at 5056/5664
Progress is at Node 5120/5664
Checkpoint saved at 5120/5664
Progress is at Node 5184/5664
Checkpoint saved at 5184/5664
Progress is at Node 5248/5664
Checkpoint saved at 5248/5664
Progress is at Node 5312/5664
Checkpoint saved at 5312/5664
Progress is at Node 5376/5664
Checkpoint saved at 5376/5664
Progress is at Node 5440/5664
Checkpoint saved at 5440/5664
Progress is at Node 5504/5664
Checkpoint saved at 5504/5664
Progress is at Node 5568/5664
Checkpoint saved at 5568/5664
Progress is at Node 5632/5664
Checkpoint saved at 5632/5664
Processed 5664 nodes. Saved to nodes/semantic_nodes_pdf_with_locations.pkl

In [14]:
with open('nodes/semantic_nodes_pdf_with_locations.pkl', 'rb') as f1, open('nodes/semantic_nodes_pdf.pkl', 'rb') as f2:
    pdf = pickle.load(f1)
print(len(pdf))

5664

## Checking

In [50]:
with open('nodes/semantic_nodes_news_with_locations.pkl', 'rb') as f1, open('nodes/semantic_nodes_pdf_with_locations.pkl', 'rb') as f2:
    newsloc = pickle.load(f1)
    pdfloc = pickle.load(f2)

In [51]:
news[0:5]

[TextNode(id_='7f718259-6e6a-4763-99f0-95d98779bdd7', embedding=None, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00', 'folder': 'natural-hazards'}, excluded_embed_metadata_keys=['source', 'fileType', 'folder'], excluded_llm_metadata_keys=['source', 'fileType', 'folder'], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='af1953aa-c3c6-4cc6-8612-b8f45b947bfd', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00'}, hash='871d056f30909516e363c7f4dc279b97a9bf6226e8278ec0171047bb4be26a91'), <NodeRelationship.NEXT: '3'>: RelatedNodeInfo(node_id='4b343516-2c45-49b7-81da-ae9e185d26b8', node_type=<ObjectType.TEXT: '1'>, metadata={}, hash='e0960491691cf6b33fabd430d77c117e96142684c7d45d790e5957a2cd28900a')}, metadata_template='{key}: {value}', metadata_separator='\n', text='The federal government allocates vast amounts of resources to protecting homes in wildfire-prone areas. Wildland firefighting costs associated with home protection are high and rising due to climate change and ongoing development in hazardous areas.\n\nNew research has mapped the costs of protecting homes from wildfires and shows that the cost of wildfire protection per home is highest in rural parts of the western United States where housing density is relatively low.\n\nIn these areas of low housing density and high wildfire risk, upfront investments in mitigation, including the use of fire-resistant building and landscaping materials, could be highly cost effective—saving lives and property, and reducing fire suppression costs.\n\nProtecting homes from wildfires is expensive Rapid suburban and exurban home development starting in the second half of the 20th century has occurred in areas bordering public lands. This has placed an increasing number of homes and lives in areas with high wildfire risk. Consequently, there is social and political pressure on federal and state agencies to safeguard lives and property while also protecting natural resources, forest health, critical watersheds, or other values at risk. Across all levels of government, particularly state and federal levels, land management agencies assume responsibility and incur high costs for protecting homes and neighborhoods from wildfires.\n\nThe cost of wildfire protection per home is highest in rural areas\n\nNew research from economists Patrick Baylis and Judson Boomhower has mapped the federal costs of protecting homes from wildfires across the 11 western states. Their findings are based on comprehensive data on firefighting expenditures from 4,665 fires affecting nearly 9 million homes and accounting for more than $13 billion in suppression costs from 1995 to 2016 (see Data Sources & Methods below).\n\nThe map below, representing Baylis’ and Boomhower’s findings, illustrates where the federal government is spending money to protect homes from wildfires and provides estimates of costs for home protection over the life of the home should trends continue. It shows that expected wildfire protection costs, on average, are highest in rural parts of the West where home density is relatively low.\n\nThe average expected protection costs are shown for all single-family homes per 15-km cell. Costs range from $1 per home to greater than $50,000 per home and vary with wildfire hazard potential, density development, and other factors. The relatively low cost estimates for Colorado reflect fewer costly, large fires in that region during the historical sample period analyzed in the paper (1995 to 2016).\n\nThe analysis also demonstrates which states have the largest number of homes with high expected protection costs if a wildfire occurs. The table below shows the total number of properties in each state that are estimated to have protection costs of more than $10,000 per home.\n\nNumber of properties in locations with extremely high wildfire protection costs.\n\nState # Properties California 138,911 Montana 79,509 Idaho 77,942 Washington 56,267 Oregon 55,062 Utah 28,672 Arizona 14,674 New Mexico 14,129 Nevada 10,739 Wyoming 3,868 Colorado 3,152\n\nCalifornia has more than 138,000 properties in areas where wildfire protection costs are expected to exceed $10,000 per home over the life of the home. Montana and Idaho each have more than 75,000 properties in areas where lifetime protection costs are expected to exceed $10,000 per home if one or more wildfires occur.\n\nCommunity investment is needed now While measures that reduce wildfire risk should be implemented in all high wildfire hazard areas, they may be especially cost effective in areas where expected home protection costs are highest. Every western state has neighborhoods where an upfront investment in mitigation would go a long way in reducing response and recovery costs paid by taxpayers. Fortunately, several cost-effective solutions can make homes safer from wildfires. They should be prioritized and integrated into legislation. Investment in neighborhood design, home mitigation, wildfire-resistant construction and landscaping, evacuation, and land use planning are essential. Specifically, communities need support and funding for: Land use planning and development of community planning documents; Enacting and improving building codes to integrate wildfire mitigation measures into site design and construction in wildfire-prone areas; Retrofitting homes, improving landscaping and property maintenance, and modifying neighborhood layout to increase wildfire resilience. We must start investing in communities now to create homes and neighborhoods better adapted to increasing wildfire risks. Data Sources and Methods Headwaters Economics collaborated with Baylis and Boomhower to represent their dataset in this post. Estimated Wildfire Protection Costs Baylis and Boomhower’s research compiled parcel-level data for single family homes in the West with firefighting expenditures from each major federal land management agency, resulting in the most comprehensive dataset on firefighting expenditures yet. Their final data set included 4,665 fires that occurred between 1995 and 2016 and accounted for $13.2 billion of suppression costs. They linked the fires to 8.6 million homes in the WUI in 11 western states (Arizona, California, Colorado, Idaho, Montana, New Mexico, Nevada, Oregon, Utah, Washington, and Wyoming). They also considered suppression data from the U.S. ', mimetype='text/plain', start_char_idx=0, end_char_idx=5546, text_template='{metadata_str}\n\n{content}'),
 TextNode(id_='4b343516-2c45-49b7-81da-ae9e185d26b8', embedding=None, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00', 'folder': 'natural-hazards'}, excluded_embed_metadata_keys=['source', 'fileType', 'folder'], excluded_llm_metadata_keys=['source', 'fileType', 'folder'], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='af1953aa-c3c6-4cc6-8612-b8f45b947bfd', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00'}, hash='871d056f30909516e363c7f4dc279b97a9bf6226e8278ec0171047bb4be26a91'), <NodeRelationship.PREVIOUS: '2'>: RelatedNodeInfo(node_id='7f718259-6e6a-4763-99f0-95d98779bdd7', node_type=<ObjectType.TEXT: '1'>, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00'}, hash='3f2cc12e510088062d023894c2b72e46016ab04fcd3a79fb35678134d5fef722'), <NodeRelationship.NEXT: '3'>: RelatedNodeInfo(node_id='99552dc3-9143-440f-973d-8bd6f4907893', node_type=<ObjectType.TEXT: '1'>, metadata={}, hash='d0de142c7070060db602266898cb7c87b0f1e8cedb7790cfab7f445123806fa2')}, metadata_template='{key}: {value}', metadata_separator='\n', text='Department of Agriculture’s Office of Inspector General in a 2006 Audit Report, Forest Service Large Fire Suppression Costs. For each of the 8.6 million homes, the researchers calculated annualized “realized” protection costs that represent the historical cost of protecting the home from wildfires. In their empirical regression analysis, Baylis and Boomhower identify the degree to which incident-level firefighting expenditures increase when homes are located in harm’s way.\n\n\n\nRealized protection costs were calculated by allocating the total expenditures dedicated to defending homes during each observed fire across individual homes and then summing these totals for all historical incidents. In short, these realized protection costs are the best estimate of what has been spent historically to protect a given home. Realized costs are then extrapolated to estimate “expected protection costs” by averaging realized costs over similar-risk groups of homes. These expected protection costs represent expected government expenditures for home protection over the life of the home should trends continue. Full methodologies are described in detail in Appendix C in Baylis and Boomhower’s published manuscript.\n\n\n\nThe researchers focused on single-family homes in the West and included topography and weather conditions in their calculations. They considered fires 300 acres or larger. Their model generated a 15-km grid for the 11 western states that estimates the total protection costs. We assigned each 15-km grid to a county. Grids that overlapped multiple counties were assigned to the county where the majority of the grid overlapped. The expected protection cost for all grids in each county were then summed. Research Conclusions Among their research conclusions, Baylis and Boomhower found: Fire protection costs can exceed 20% of home value in the West. Half of the homes in high wildfire risk areas in the West have expected protection costs of $2,300 or less. However, 5% of homes have costs nearing $12,000, and 1% of homes have costs exceeding $38,000, according to the analysis. These estimates include expenditures for equipment, firefighter salaries, aviation, and other related home protection costs.\n\nHalf of the homes in high wildfire risk areas in the West have expected protection costs of $2,300 or less. However, 5% of homes have costs nearing $12,000, and 1% of homes have costs exceeding $38,000, according to the analysis. These estimates include expenditures for equipment, firefighter salaries, aviation, and other related home protection costs. Higher protection costs are associated with higher fire risk areas. Average home protection costs are clearly linked to the local wildfire hazard potential. According to the research, expected protection costs are highest in Northern California, central Oregon and Washington, Idaho, and western Montana because those areas are sparsely populated and have many areas of high fire hazard. In these remote areas, protection costs can be tens of thousands of dollars per home.\n\nAverage home protection costs are clearly linked to the local wildfire hazard potential. According to the research, expected protection costs are highest in Northern California, central Oregon and Washington, Idaho, and western Montana because those areas are sparsely populated and have many areas of high fire hazard. In these remote areas, protection costs can be tens of thousands of dollars per home. Protection costs decrease as development density increases. Residential development dramatically increases firefighting costs. The presence of just one to 32 homes almost doubles expenditures on a fire. However, once a development reaches a relatively moderate density (100-300 homes), additional homes have little effect on costs. That is, the cost of protection per home does not increase significantly once the density of homes has reached a particular threshold. The research findings indicate the cost of protecting hundreds of homes in harm’s way is not significantly more than protecting dozens of homes. Baylis, Patrick, and Judson Boomhower. ', mimetype='text/plain', start_char_idx=5546, end_char_idx=9657, text_template='{metadata_str}\n\n{content}'),
 TextNode(id_='99552dc3-9143-440f-973d-8bd6f4907893', embedding=None, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00', 'folder': 'natural-hazards'}, excluded_embed_metadata_keys=['source', 'fileType', 'folder'], excluded_llm_metadata_keys=['source', 'fileType', 'folder'], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='af1953aa-c3c6-4cc6-8612-b8f45b947bfd', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00'}, hash='871d056f30909516e363c7f4dc279b97a9bf6226e8278ec0171047bb4be26a91'), <NodeRelationship.PREVIOUS: '2'>: RelatedNodeInfo(node_id='4b343516-2c45-49b7-81da-ae9e185d26b8', node_type=<ObjectType.TEXT: '1'>, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00'}, hash='878332df7f1d4924bde613fd1bca1fabf06164d1b0bf8a7aab9b74218769d7bc'), <NodeRelationship.NEXT: '3'>: RelatedNodeInfo(node_id='43cc66f5-3ce2-4c43-923b-7d9e60863c72', node_type=<ObjectType.TEXT: '1'>, metadata={}, hash='21b837609eb2938682bf1f7c5cd8921b72f42128429b57623cfc50f2d6e0ce58')}, metadata_template='{key}: {value}', metadata_separator='\n', text='2023. “The Economic Incidence of Wildfire Suppression in the United States.” American Economic Journal: Applied Economics, 15 (1): 442-73. Demographic Data Demographic data in the visualization above are from the U.S. Census Bureau’s American Community Survey five-year average for 2017-2021. Wildfire Risk Data Wildfire Risk data in the visualization above are from Wildfire Risk to Communities and represent the risk to homes ranked against other western U.S. communities and within each state. ', mimetype='text/plain', start_char_idx=9657, end_char_idx=10154, text_template='{metadata_str}\n\n{content}'),
 TextNode(id_='43cc66f5-3ce2-4c43-923b-7d9e60863c72', embedding=None, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00', 'folder': 'natural-hazards'}, excluded_embed_metadata_keys=['source', 'fileType', 'folder'], excluded_llm_metadata_keys=['source', 'fileType', 'folder'], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='af1953aa-c3c6-4cc6-8612-b8f45b947bfd', node_type=<ObjectType.DOCUMENT: '4'>, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00'}, hash='871d056f30909516e363c7f4dc279b97a9bf6226e8278ec0171047bb4be26a91'), <NodeRelationship.PREVIOUS: '2'>: RelatedNodeInfo(node_id='99552dc3-9143-440f-973d-8bd6f4907893', node_type=<ObjectType.TEXT: '1'>, metadata={'source': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'title': 'New research shows where wildfire mitigation can be highly cost effective', 'url': 'https://headwaterseconomics.org/natural-hazards/wildfire-suppression-costs-rising/', 'published_date': '2023-01-05 17:40:50+00:00'}, hash='bc02bbe5c09192bc5972e37932248ce7e513c7a86d0ae2c806e959021e0a4dd2'), <NodeRelationship.NEXT: '3'>: RelatedNodeInfo(node_id='e58eec39-3c76-494e-913f-a6f78f8a1a12', node_type=<ObjectType.TEXT: '1'>, metadata={}, hash='af3f94a039f35ac9dd19f2060f1d4aef4b817718ab9b492a764cc55846ee655a')}, metadata_template='{key}: {value}', metadata_separator='\n', text='Limitations The analysis in this post is based on a model of historical data and modeling assumptions, and thus does not perfectly predict future outcomes. The relatively low cost estimates for Colorado reflect fewer costly, large fires in that region during the historical sample period analyzed in the paper (1995 to 2016). For questions and inquiries regarding methodologies and analysis of federal protection costs, please contact Patrick Baylis at patrick.baylis@ubc.ca and Judson Boomhower at jboomhower@ucsd.edu.\n\n', mimetype='text/plain', start_char_idx=10154, end_char_idx=10675, text_template='{metadata_str}\n\n{content}'),

In [32]:
news_data = []
for node in newsloc:
    temp=node.metadata
    temp['Text']=node.text
    news_data.append(temp)

df = pd.DataFrame(news_data)
df

,source,title,url,folder,extracted_geographies,most_common_location,Text
0,None,New research shows where wildfire mitigation c...,None,,"[United States, Colorado]",California,The federal government allocates vast amounts ...
1,None,New research shows where wildfire mitigation c...,None,,[West],Montana,Department of Agriculture’s Office of Inspecto...
2,None,New research shows where wildfire mitigation c...,None,,"[United States, U. S.]",United States,2023. “The Economic Incidence of Wildfire Supp...
3,None,New research shows where wildfire mitigation c...,None,,[Colorado],Colorado,Limitations The analysis in this post is based...
4,None,New research shows where wildfire mitigation c...,None,,[],None,Acknowledgments\n\nIn addition to their valuab...
...,...,...,...,...,...,...,...
7306,None,"Farmworkers feed the country, but who protects...",None,,"[Oxnard, Calif, A, Los Angeles County, Ventura...",NaN,"Farmworkers feed the country, but who protects..."
7307,None,"Farmworkers feed the country, but who protects...",None,,"[California, Northern L. A., Oregon, Los Angel...",NaN,is to the state's agricultural region. Drive a...
7308,None,"Farmworkers feed the country, but who protects...",None,,[],NaN,"These are folks without a social safety net,"" ..."
7309,None,"Farmworkers feed the country, but who protects...",None,,"[Southern California, California]",NaN,The outlook for California wildfires is grim s...
7310,None,"Farmworkers feed the country, but who protects...",None,,[Ventura County],NaN,"""They have no other choice but to work.""\n\nTo..."

In [49]:
with open('nodes/semantic_nodes_news.pkl', 'rb') as f1, open('nodes/semantic_nodes_pdf.pkl', 'rb') as f2:
    news = pickle.load(f1)
    pdf = pickle.load(f2)

In [31]:
news_full = []
for node in news:
    temp=node.metadata
    temp['Text']=node.text
    news_full.append(temp)

df_full= pd.DataFrame(news_full)
df_full

,source,title,url,published_date,folder,Text
0,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,2023-01-05 17:40:50+00:00,natural-hazards,The federal government allocates vast amounts ...
1,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,2023-01-05 17:40:50+00:00,natural-hazards,Department of Agriculture’s Office of Inspecto...
2,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,2023-01-05 17:40:50+00:00,natural-hazards,2023. “The Economic Incidence of Wildfire Supp...
3,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,2023-01-05 17:40:50+00:00,natural-hazards,Limitations The analysis in this post is based...
4,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,2023-01-05 17:40:50+00:00,natural-hazards,Acknowledgments\n\nIn addition to their valuab...
...,...,...,...,...,...,...
7306,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,2025-01-31 00:00:00,nx-s1-5276397,"Farmworkers feed the country, but who protects..."
7307,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,2025-01-31 00:00:00,nx-s1-5276397,is to the state's agricultural region. Drive a...
7308,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,2025-01-31 00:00:00,nx-s1-5276397,"These are folks without a social safety net,"" ..."
7309,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,2025-01-31 00:00:00,nx-s1-5276397,The outlook for California wildfires is grim s...
7310,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,2025-01-31 00:00:00,nx-s1-5276397,"""They have no other choice but to work.""\n\nTo..."

In [34]:
df_merged = df.copy()
df_merged[["source", "url", "published_date", "folder"]] = df_full[
    ["source", "url", "published_date", "folder"]
]

df_merged

,source,title,url,folder,extracted_geographies,most_common_location,Text,published_date
0,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,natural-hazards,"[United States, Colorado]",California,The federal government allocates vast amounts ...,2023-01-05 17:40:50+00:00
1,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,natural-hazards,[West],Montana,Department of Agriculture’s Office of Inspecto...,2023-01-05 17:40:50+00:00
2,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,natural-hazards,"[United States, U. S.]",United States,2023. “The Economic Incidence of Wildfire Supp...,2023-01-05 17:40:50+00:00
3,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,natural-hazards,[Colorado],Colorado,Limitations The analysis in this post is based...,2023-01-05 17:40:50+00:00
4,https://headwaterseconomics.org/natural-hazard...,New research shows where wildfire mitigation c...,https://headwaterseconomics.org/natural-hazard...,natural-hazards,[],None,Acknowledgments\n\nIn addition to their valuab...,2023-01-05 17:40:50+00:00
...,...,...,...,...,...,...,...,...
7306,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,nx-s1-5276397,"[Oxnard, Calif, A, Los Angeles County, Ventura...",NaN,"Farmworkers feed the country, but who protects...",2025-01-31 00:00:00
7307,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,nx-s1-5276397,"[California, Northern L. A., Oregon, Los Angel...",NaN,is to the state's agricultural region. Drive a...,2025-01-31 00:00:00
7308,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,nx-s1-5276397,[],NaN,"These are folks without a social safety net,"" ...",2025-01-31 00:00:00
7309,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,nx-s1-5276397,"[Southern California, California]",NaN,The outlook for California wildfires is grim s...,2025-01-31 00:00:00
7310,https://www.npr.org/2025/01/31/nx-s1-5276397/w...,"Farmworkers feed the country, but who protects...",https://www.npr.org/2025/01/31/nx-s1-5276397/w...,nx-s1-5276397,[Ventura County],NaN,"""They have no other choice but to work.""\n\nTo...",2025-01-31 00:00:00

In [44]:
idx = 0  # change to any index
print("Title", df_merged.loc[idx, "title"])
print("Text:\n", df_merged.loc[idx, "Text"])
print("\nLocation:", df_merged.loc[idx, "extracted_geographies"])

Title New research shows where wildfire mitigation can be highly cost effective
Text:
 The federal government allocates vast amounts of resources to protecting homes in wildfire-prone areas. Wildland firefighting costs associated with home protection are high and rising due to climate change and ongoing development in hazardous areas.

New research has mapped the costs of protecting homes from wildfires and shows that the cost of wildfire protection per home is highest in rural parts of the western United States where housing density is relatively low.

In these areas of low housing density and high wildfire risk, upfront investments in mitigation, including the use of fire-resistant building and landscaping materials, could be highly cost effective—saving lives and property, and reducing fire suppression costs.

Protecting homes from wildfires is expensive Rapid suburban and exurban home development starting in the second half of the 20th century has occurred in areas bordering public lands. This has placed an increasing number of homes and lives in areas with high wildfire risk. Consequently, there is social and political pressure on federal and state agencies to safeguard lives and property while also protecting natural resources, forest health, critical watersheds, or other values at risk. Across all levels of government, particularly state and federal levels, land management agencies assume responsibility and incur high costs for protecting homes and neighborhoods from wildfires.

The cost of wildfire protection per home is highest in rural areas

New research from economists Patrick Baylis and Judson Boomhower has mapped the federal costs of protecting homes from wildfires across the 11 western states. Their findings are based on comprehensive data on firefighting expenditures from 4,665 fires affecting nearly 9 million homes and accounting for more than $13 billion in suppression costs from 1995 to 2016 (see Data Sources & Methods below).

The map below, representing Baylis’ and Boomhower’s findings, illustrates where the federal government is spending money to protect homes from wildfires and provides estimates of costs for home protection over the life of the home should trends continue. It shows that expected wildfire protection costs, on average, are highest in rural parts of the West where home density is relatively low.

The average expected protection costs are shown for all single-family homes per 15-km cell. Costs range from $1 per home to greater than $50,000 per home and vary with wildfire hazard potential, density development, and other factors. The relatively low cost estimates for Colorado reflect fewer costly, large fires in that region during the historical sample period analyzed in the paper (1995 to 2016).

The analysis also demonstrates which states have the largest number of homes with high expected protection costs if a wildfire occurs. The table below shows the total number of properties in each state that are estimated to have protection costs of more than $10,000 per home.

Number of properties in locations with extremely high wildfire protection costs.

State # Properties California 138,911 Montana 79,509 Idaho 77,942 Washington 56,267 Oregon 55,062 Utah 28,672 Arizona 14,674 New Mexico 14,129 Nevada 10,739 Wyoming 3,868 Colorado 3,152

California has more than 138,000 properties in areas where wildfire protection costs are expected to exceed $10,000 per home over the life of the home. Montana and Idaho each have more than 75,000 properties in areas where lifetime protection costs are expected to exceed $10,000 per home if one or more wildfires occur.

Community investment is needed now While measures that reduce wildfire risk should be implemented in all high wildfire hazard areas, they may be especially cost effective in areas where expected home protection costs are highest. Every western state has neighborhoods where an upfront investment in mitigation would go a long way in reducing response and recovery costs paid by taxpayers. Fortunately, several cost-effective solutions can make homes safer from wildfires. They should be prioritized and integrated into legislation. Investment in neighborhood design, home mitigation, wildfire-resistant construction and landscaping, evacuation, and land use planning are essential. Specifically, communities need support and funding for: Land use planning and development of community planning documents; Enacting and improving building codes to integrate wildfire mitigation measures into site design and construction in wildfire-prone areas; Retrofitting homes, improving landscaping and property maintenance, and modifying neighborhood layout to increase wildfire resilience. We must start investing in communities now to create homes and neighborhoods better adapted to increasing wildfire risks. Data Sources and Methods Headwaters Economics collaborated with Baylis and Boomhower to represent their dataset in this post. Estimated Wildfire Protection Costs Baylis and Boomhower’s research compiled parcel-level data for single family homes in the West with firefighting expenditures from each major federal land management agency, resulting in the most comprehensive dataset on firefighting expenditures yet. Their final data set included 4,665 fires that occurred between 1995 and 2016 and accounted for $13.2 billion of suppression costs. They linked the fires to 8.6 million homes in the WUI in 11 western states (Arizona, California, Colorado, Idaho, Montana, New Mexico, Nevada, Oregon, Utah, Washington, and Wyoming). They also considered suppression data from the U.S.

Location: ['United States', 'Colorado']

In [56]:
test_text = """
Wildfire risk has increased across the Klamath River Basin, especially near the Klamath River and Trinity River in northern California. 
The fire also affected communities near the Sierra Nevada mountains, the Cascade Range, and the San Juan Mountains. 
Several nearby valleys, including the Sacramento Valley, Rogue Valley, and San Luis Valley, experienced heavy smoke impacts. 
Officials also coordinated with tribal governments and communities on the Yurok Reservation, Hoopa Valley Reservation, Navajo Nation, and Flathead Indian Reservation.
"""
sentences=Sentence(test_text)
tagger.predict(sentences)
extract_locations_from_sentence(sentences)

['Cascade Range',
 'Sacramento Valley',
 'Rogue Valley',
 'Hoopa Valley Reservation',
 'Klamath River',
 'Klamath River Basin',
 'San Juan Mountains',
 'California',
 'Yurok Reservation',
 'Sierra Nevada',
 'Trinity River']